[package]
name = "tessen-wave"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-complex = "0.4.0"
num-traits = "0.2.14"
nalgebra = "0.30.1"
[dev-dependencies]
float-cmp = "0.9.0"